### ISSUE TITLE
TypeScript error in temporal-spec/index.d.ts

### ISSUE THREAD

**Issue by weslord** [fullcalendar/temporal#10]
Using temporal-polyfill v0.0.7 & temporal-spec v0.0.2, I get a TypeScript error when I run `npx tsc`:

```
node_modules/temporal-spec/index.d.ts:1544:4 - error TS1036: Statements are not allowed in ambient contexts.

1544   };
        ~


Found 1 error in node_modules/temporal-spec/index.d.ts:1544
```

Going into my node_modules folder and removing the offending semicolon seems to fix the problem.

**Comment by arshaw** [comment]
Thank you so much for this report. This has been fixed [in the most recent release](https://github.com/fullcalendar/temporal/blob/main/packages/temporal-polyfill/CHANGELOG.md#v008-2022-08-24)
