### ISSUE TITLE
Temporal.Now isn't returning current date but 1970-1-20

### ISSUE THREAD

**Issue by JulianKragt** [fullcalendar/temporal#5]
Temporal.Now isn't giving the current date

this img is from this polyfill
![image](https://user-images.githubusercontent.com/18495180/155901950-356920a5-4285-488c-814d-55c3b71a56c9.png)

this img below is from the temporal docs site
![image](https://user-images.githubusercontent.com/18495180/155902022-bb52d218-1018-4534-afb4-4e9a072c2386.png)

**Comment by JulianKragt** [comment]
i think the problem is with that Temporal js doesn't have a converter for unix timestamp (that has 10 digits).
but they have for a epochNanoseconds (that has 19 digits);

**Comment by JulianKragt** [comment]
By the polyfill there seems to be 3 digits missing (16 digits).
![image](https://user-images.githubusercontent.com/18495180/155902677-a4185529-0b6e-4c11-943f-44ec39f65697.png)

but by the Temporal docs website there are 19 digits.
![image](https://user-images.githubusercontent.com/18495180/155902691-b3c14dda-991d-40ba-9c5d-8a36a2cd1a0b.png)

**Comment by arshaw** [comment]
Thanks for the report. This has been fixed in 0.0.4
