### ISSUE TITLE
Now returns the wrong date

### ISSUE THREAD

**Issue by Ayc0** [fullcalendar/temporal#7]
I'm in the timezone `Europe/Paris` at the moment and (I don't know if it's related or not), when I run `Now.instant().toLocaleString()`, I have a 2h offset from my actual time (represented here by `new Date().toLocaleString()` and it seems to match my timezone offset: UTC+2)

See [runkit](https://runkit.com/ayc0/62415cfdad5a030008a8422c):

<img width="483" alt="image" src="https://user-images.githubusercontent.com/22725671/160343494-bab867ff-4c81-4191-adc5-4f96d1ceafeb.png">

**Comment by arshaw** [comment]
the Instant object always outputs strings in UTC regardless of the current timezone (or any timezone really).

you should use ZonedDateTime instead:
https://runkit.com/arshaw/624b5c68af51730008492316
